# Generated by Django 4.1.13 on 2024-06-08 13:13

from django.db import migrations, models
import videos.standard


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(storage=videos.standard.VideoMediaCloudinaryStorage(), upload_to='videos'),
        ),
    ]
