# Generated by Django 4.1.13 on 2024-06-10 06:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video_file'),
        ),
    ]
